import type { Project } from '@/domain/planner/types'
import type { ShoppingRow } from '@/domain/planner/budget'

export interface ExportNaming {
  deviceName: (catalogId: string) => string
  floorName: (level: number) => string
  roomName: (name: string, type: string) => string
}

function yamlQuote(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

/**
 * A Home Assistant starter file: the floors and areas to create (HA manages
 * these in its UI registry, so this is a guided checklist rather than
 * importable config) plus every planned device as a per-area shopping list.
 */
export function toHomeAssistantYaml(project: Project, naming: ExportNaming): string {
  const lines: string[] = [
    '# Generated by Foyer — https://github.com/stvncode',
    '# Home Assistant manages floors and areas in its UI registry',
    '# (Settings → Areas, labels & zones), so use this file as a checklist:',
    '# create each floor and area below, then assign devices as you pair them.',
    '',
    'floors:',
  ]
  const sortedFloors = [...project.floors].sort((a, b) => a.level - b.level)
  for (const floor of sortedFloors) {
    lines.push(`  - name: ${yamlQuote(floor.name || naming.floorName(floor.level))}`)
    lines.push(`    level: ${floor.level}`)
  }
  lines.push('', 'areas:')
  for (const floor of sortedFloors) {
    for (const room of floor.rooms) {
      lines.push(`  - name: ${yamlQuote(naming.roomName(room.name, room.type))}`)
      lines.push(`    floor: ${yamlQuote(floor.name || naming.floorName(floor.level))}`)
      if (room.devices.length > 0) {
        lines.push('    planned_devices:')
        for (const device of room.devices) {
          lines.push(`      - ${yamlQuote(naming.deviceName(device.catalogId))} # x${device.qty}`)
        }
      }
    }
  }
  lines.push('')
  return lines.join('\n')
}

function csvField(value: string | number): string {
  const text = String(value)
  return /[",\n;]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text
}

/** Shopping list as CSV, ready for a spreadsheet or a quote request */
export function toShoppingCsv(
  rows: ShoppingRow[],
  headers: { device: string; category: string; rooms: string; qty: string; unit: string; total: string },
  naming: Pick<ExportNaming, 'deviceName'>,
): string {
  const lines = [
    [headers.device, headers.category, headers.rooms, headers.qty, headers.unit, headers.total]
      .map(csvField)
      .join(','),
  ]
  for (const row of rows) {
    lines.push(
      [
        csvField(naming.deviceName(row.item.id)),
        csvField(row.item.category),
        csvField(row.rooms.join(' / ')),
        row.qty,
        row.item.priceEur,
        row.total,
      ].join(','),
    )
  }
  return lines.join('\n') + '\n'
}
